### ISSUE TITLE
Bug when redrawing on window resize

### ISSUE THREAD

**Issue by jstressman** [HaikuArchives/FontBoy#12]
![fontboyresizebug1](https://cloud.githubusercontent.com/assets/973348/6074651/16a08ab2-ad91-11e4-9ae6-379541cff298.png)

**Comment by janus2** [comment]
I can't reproduce the problem. Can you tell me the font size and the columns settings? is systematic?

**Comment by jstressman** [comment]
![screenshot57](https://cloud.githubusercontent.com/assets/973348/6097588/daae15c6-af91-11e4-9602-b367b1c874cc.png)

It should basically be the default. I haven't changed anything other than resizing the window.

I just downloaded master again and rebuilt just to make sure it was still there, and I'm still seeing the same problem.

**Comment by janus2** [comment]
Thanks, I had too many fonts...
Now I can reproduce the glitch.

**Comment by jstressman** [comment]
Confirmed that change fixes it for me as well. Thanks!
