### ISSUE TITLE
Add the possibility to change the selected text color, selected height lines color, ...

### ISSUE THREAD

**Issue by janus2** [HaikuArchives/FontBoy#9]
Add the possibility to change the 
- Selected list text color
- Selected list height lines color
- Selected list info text
- Selected details text color

Change the List selection to List selection background
Change the Details selection to Details selection background

Without this it's difficult to customize the selection

**Comment by pulkomandy** [comment]
Hi,
Do you plan to work on this?  I think I will wait until it is done and then prepare a new FontBoy release since you did a great work with improving the app so far.

**Comment by janus2** [comment]
Yes, I'll do it very soon.
